language: php

php:
    - 5.6

before_install:
    - sudo chmod 0777 -R app/logs/ app/cache/

install:
    - composer install -n --prefer-source

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - app/console doctrine:database:create -e test

script:
    - php app/console doctrine:schema:drop --force
    - php app/console doctrine:schema:create
    - php app/console doctrine:schema:update --force
    - php app/console doctrine:fixtures:load --no-interaction
    - phpunit -c app --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover