language: php

php:
    - 5.6

before_install:
    - sudo chmod 0777 -R app/logs/ app/cache/

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer install
    - app/console doctrine:database:create -e test

script:
    - php app/console doctrine:schema:drop --force
    - php app/console doctrine:schema:create
    - php app/console doctrine:schema:update --force
    - phpunit -c app
