<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository
{
    public function findAllDatesForChoiceField()
    {
        $query = $this->createQueryBuilder('c')
            ->orderBy('c.createdAt', 'DESC')
            ->groupBy('c.createdAt')
            ->getQuery();

        $dateChoices = array();
        foreach($query->getResult() as $uniqueDateCurrency){
            $dateChoices[$uniqueDateCurrency->getCreatedAt()->format("Y-m-d")] = $uniqueDateCurrency->getCreatedAt()->format("Y-m-d");
        }
        return $dateChoices;
    }

    public function findRateByDateAndShortNameAndCurrency($date, $shortName, $currency)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.createdAt = :date')
            ->andWhere('c.sourceShortName = :shortName')
            ->andWhere('c.currency = :currency')
            ->setParameter('date', $date)
            ->setParameter('shortName', $shortName)
            ->setParameter('currency', $currency)
            ->getQuery();

        return $query->getSingleResult();
    }

}
