<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository
{
    public function findRateByDateAndShortNameAndCurrency($date, $shortName, $currency)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Source s
                JOIN AppBundle:Currency c
                WHERE s.createdAt = :date AND s.shortCode = :short_code AND c.currency = :currency'
            )->setParameter('date', $date)
            ->setParameter('short_code', $shortName)
            ->setParameter('currency', $currency)
            ->setMaxResults(1);

        return $query->getOneOrNullResult();
    }

    public function findAllCurrenciesForChoiceField()
    {
        $query = $this->createQueryBuilder('c')
            ->select('c.currency')
            ->orderBy('c.currency', 'ASC')
            ->groupBy('c.currency')
            ->getQuery();

        $currencyChoices = array();
        foreach($query->getResult() as $uniqueCurrency){
            $currencyChoices[$uniqueCurrency['currency']] = $uniqueCurrency['currency'];
        }
        return $currencyChoices;
    }
}
